<h2>Competences</h2>


<div>
        <p>Voici les technologies et les langages que j'ai acquis jusqu'à présent.</p>
        <ul>
                <li class="skullsBackground">
                        <div>
                                <p id="html"><strong id="leftSkull">HTML</strong><span id="rightSkull">95%</span></p>
                        </div>
                        <div class="">
                                <p class="rightSide">HTML 5</p>
                        </div>
                </li>
                <li class="skullsBackground">
                        <div>
                                <p id="css"><strong id="leftSkull">CSS</strong><span id="rightSkull">90%</span></p>

                        </div>
                        <div class="">
                                <p class="rightSide">CSS3, SASS, Responsive Design, Bootstrap</p>
                        </div>
                </li>
                <li class="skullsBackground">
                        <div>
                                <p id="php"><strong id="leftSkull">PHP</strong><span id="rightSkull">60%</span></p>
                        </div>
                        <div>
                                <p class="rightSide">Modele MVC, POO, PDO</p>
                        </div>
                </li>
                <li class="skullsBackground">
                        <div>
                                <p  id="javascript"><strong id="leftSkull">Javascript</strong><span id="rightSkull">60%</span></p>
                        </div>
                        <div>
                                <p class="rightSide">Ajax, Jquery, SVG</p>
                        </div>
                </li>
                <li class="skullsBackground">
                        <div>
                                <p  id="mysql"><strong id="leftSkull">MySql</strong><span id="rightSkull">50%</span></p>
                        </div>
                        <div>
                                <p class="rightSide">Création de base de données, requêtes SQL</p>
                        </div>
                </li>
                <li class="skullsBackground">
                        <div>
                                <p  id="other"><strong id="leftSkull">Autres</strong></p>
                        </div>
                        <div>
                                <p class="rightSide">Terminal, Github, GitKraken, Prepos</p>
                        </div>
                </li>
        </ul>

</div>

<div>

        <p>Je travaille actuellement sur un projet personnel en autodidacte sur Django, associé à Javascript et SqLite</p>


</div>
