<h2>Contact</h2>
        <p>Pour une prise de contact rapide, vous pouvez remplir ce formulaire :-)</p>

        <p> <?= $sErrorDisplay ?></p>
<form class="" action="#" method="post">
                        <!-- <fieldset> -->
                                <label for="name">Nom Prénom : </label><input type="text" name="name" placeholder="Nom et prénom">
                        <!-- </fieldset> -->
                        <fieldset>
                                <label for="mail">Mail : </label><input type="text" name="mail" placeholder="Entrez votre mail">
                        </fieldset>
                        <fieldset>
                                <label for="content">Contenu : </label><textarea name="content" rows="5" cols="30" ></textarea>
                        </fieldset>
                        <div class="captcha">
                                <div class="g-recaptcha" data-sitekey="6LduRzYUAAAAALBtvZEv0gBchEUL63QMN537jleW" data-theme='dark'></div>
                        </div>
                        <button type="submit" name="sendMail" id="downCaptcha">Envoyer</button>
</form>
