<footer>
        <ul id='social'>
                <li>
                        <a href="https://www.instagram.com/dj_c_one/?hl=fr" target="_blank"><img src="public/img/instagram.svg" alt="instagram"></a>
                </li>
                <li>
                        <a href="https://www.facebook.com/Minidou.HipHop" target="_blank"><img src="public/img/social-media.svg" alt="Facebook"></a>
                </li>
                <li>
                        <a href="https://www.linkedin.com/in/c%C3%A9dric-leuiller-37b3a4123/" target="_blank"><img src="public/img/linkedin.svg" alt="Linkedin"></a>
                </li>
                <li>
                        <a href="https://github.com/cedricleuiller" target="_blank"><img src="public/img/github.svg" alt="Github"></a>
                </li>
        </ul>
        <small>Ce site à été créé par <a href="/portfolio/index.php">Cédric Leuiller</a>.</small>
</footer>
