<ul id='social'>
        <li>
                <a href="https://www.linkedin.com/in/c%C3%A9dric-leuiller-37b3a4123/" target="_blank"><img src="public/img/linkedin.svg" alt="Linkedin"></a>
        </li>
        <li>
                <a href="https://github.com/cedricleuiller" target="_blank"><img src="public/img/github.svg" alt="Github"></a>
        </li>
</ul>
<small>Ce site à été créé par <a href="/portfolio/index.php">Cédric Leuiller</a>.</small>
