<h1>Cédric Leuiller</h1>
<h2>Développeur Web</h2>

<nav class="light">
        <a href="index.php?page=home" id="presentationForm">Presentation</a>
        <a href="index.php?page=competences" id="skill">Competences</a>
        <a href="index.php?page=works" id="product">Realisations</a>
        <a href="index.php?page=contact" id="contact">Contact</a>
        <a href="index.php?page=newWork">Ajouter une realisation</a>
        <a href="index.php?page=mailList">Afficher mes demandes de contact</a>
</nav>
