
<h2>Presentation</h2>
<p>Bonjour,</p>
<p>Je m'appelle Cédric Leuiller,</p>
<p>j'ai commencé le développement web pour développer un petit site personnel et c'est rapidement devenu une vraie vocation.</p>
<p>Dès lors, j'ai suivi une formation de développeur intégrateur web a l'école de la 3W Academy (Paris 18ème) diplomante d'un RNCP niveau 3 (BAC+2)</p>
<p>J'aime expérimenter, découvrir et apprendre au fur et à mesure de mes projets professionnels et personnels.</p>
<p>Ce site sera adapté pour mobiles et tablettes d'ici peu, il sera aussi en constante évolution jusqu'à l'obtention de mon objectif final !</p>
