<!DOCTYPE html>
<html>
<head>
        <meta charset="utf-8">
        <title> <?= $title ?> </title>
        <meta name="description" content=" <?= $description ?>">
        <link rel="stylesheet" href="public/fonts/font_awesome/css/font-awesome.min.css">
        <link rel="stylesheet" href="public/css/normalize.css">
        <link rel="stylesheet" href="public/css/style.css">
        <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
        <script src='https://www.google.com/recaptcha/api.js'></script>
</head>
<body>
        <header class="header">
                <?php
                require 'controllers/header.php';
                ?>
        </header>
        <main id="container">
                <?php
                require 'controllers/'.$sPage.'.php';
                 ?>
        </main>
        <footer>
                <?php
                require 'controllers/mailSend.php';
                require 'controllers/footer.php';
                ?>
        </footer>
        <script type="text/javascript" src="public/scripts/main.js"></script>
</body>
</html>
