<!DOCTYPE html>
<html>
<head>
        <meta charset="utf-8">
        <meta name="description" content=" <?= $description ?> ">
        <title>Portfolio de Cédric Leuiller</title>
        <link rel="stylesheet" href="public/fonts/font_awesome/css/font-awesome.min.css">
        <link rel="stylesheet" href="public/css/normalize.css">
        <link rel="stylesheet" href="public/css/style.css">
        <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
</head>
<body>
        <main>
                <div id="cookieAlert">
                        <p>Ce site utilise un cookie pour une meilleure expérience sur le site ! <input type="submit" name="cookieInfo" value="En savoir plus" onclick='cookieRedirect()'> </p>
                </div>
                <section id="welcome">
                        <p id='firstLine' class="welcome"></p>
                        <p id="secondLine" class="welcome"></p>
                        <p id="thirdLine" class="welcome"></p>
                </section>
                <div id="skip">
                        <a href="http://cedric-leuiller.fr">SKIP INTRO</a>
                </div>

                <script type="text/javascript" src="public/scripts/welcome.js"></script>
        </main>

</body>
</html>
